use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_c(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "/* Generated by SettingSpec */\n\n#ifndef SETTINGS_H\n#define SETTINGS_H\n\n#include <stdbool.h>\n#include <stddef.h>\n\n",
    );

    let mut struct_defs = String::new();
    let root_type = generate_c_structs(&tree, "Settings", &mut struct_defs);

    out.push_str(&struct_defs);

    let mut init_vals = String::new();
    format_c_init(&tree, 1, &mut init_vals);

    out.push_str(&format!(
        "static const {} settings = {{\n{}}};\n\n#endif /* SETTINGS_H */\n",
        root_type, init_vals
    ));

    Ok(out)
}

fn generate_c_structs(
    map: &IndexMap<String, ConfigNode>,
    struct_name: &str,
    out: &mut String,
) -> String {
    let mut fields = Vec::new();

    for (k, node) in map {
        let field_name = sanitize_c_identifier(k);
        match node {
            ConfigNode::Null => {
                fields.push(format!("    const void* {};", field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::String(_) | TomlValue::Datetime(_) => {
                    fields.push(format!("    const char* {};", field_name));
                }
                TomlValue::Integer(_) => {
                    fields.push(format!("    long long {};", field_name));
                }
                TomlValue::Float(_) => {
                    fields.push(format!("    double {};", field_name));
                }
                TomlValue::Boolean(_) => {
                    fields.push(format!("    bool {};", field_name));
                }
                TomlValue::Array(arr) => {
                    let (type_str, len) = c_array_type(arr);
                    fields.push(format!("    {} {}[{}];", type_str, field_name, len.max(1)));
                    fields.push(format!("    size_t {}_len;", field_name));
                }
                TomlValue::Table(tbl) => {
                    let sub_name = format!("{}{}", struct_name, capitalize(k));
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    let sub_type = generate_c_structs(&sub_map, &sub_name, out);
                    fields.push(format!("    {} {};", sub_type, field_name));
                }
            },
            ConfigNode::Map(sub_map) => {
                let sub_name = format!("{}{}", struct_name, capitalize(k));
                let sub_type = generate_c_structs(sub_map, &sub_name, out);
                fields.push(format!("    {} {};", sub_type, field_name));
            }
        }
    }

    let struct_def = format!(
        "typedef struct {{\n{}\n}} {};\n\n",
        fields.join("\n"),
        struct_name
    );
    out.push_str(&struct_def);
    struct_name.to_string()
}

fn format_c_init(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    for (k, node) in map {
        let field_name = sanitize_c_identifier(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}.{} = NULL,\n", indent, field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Boolean(b) => {
                    out.push_str(&format!("{}.{} = {},\n", indent, field_name, b));
                }
                TomlValue::Array(arr) => {
                    let items: Vec<String> = arr
                        .iter()
                        .map(|item| match item {
                            TomlValue::Boolean(b) => b.to_string(),
                            _ => format_scalar_literal(item).unwrap_or_else(|| "\"\"".to_string()),
                        })
                        .collect();
                    out.push_str(&format!(
                        "{}.{} = {{ {} }},\n{}.{}_len = {},\n",
                        indent,
                        field_name,
                        items.join(", "),
                        indent,
                        field_name,
                        arr.len()
                    ));
                }
                TomlValue::Table(tbl) => {
                    out.push_str(&format!("{}.{} = {{\n", indent, field_name));
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    format_c_init(&sub_map, indent_level + 1, out);
                    out.push_str(&format!("{}}},\n", indent));
                }
                _ => {
                    if let Some(lit) = format_scalar_literal(v) {
                        out.push_str(&format!("{}.{} = {},\n", indent, field_name, lit));
                    }
                }
            },
            ConfigNode::Map(sub_map) => {
                out.push_str(&format!("{}.{} = {{\n", indent, field_name));
                format_c_init(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}},\n", indent));
            }
        }
    }
}

fn c_array_type(arr: &[TomlValue]) -> (&'static str, usize) {
    if arr.is_empty() {
        return ("const char*", 0);
    }
    let elem_type = match &arr[0] {
        TomlValue::Integer(_) => "long long",
        TomlValue::Float(_) => "double",
        TomlValue::Boolean(_) => "bool",
        _ => "const char*",
    };
    (elem_type, arr.len())
}

fn sanitize_c_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "auto"
            | "break"
            | "case"
            | "char"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extern"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "inline"
            | "int"
            | "long"
            | "register"
            | "restrict"
            | "return"
            | "short"
            | "signed"
            | "sizeof"
            | "static"
            | "struct"
            | "switch"
            | "typedef"
            | "union"
            | "unsigned"
            | "void"
            | "volatile"
            | "while"
    );

    if is_keyword || !is_valid_identifier(name) {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    } else {
        name.to_string()
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}
