use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_cpp(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "// Generated by SettingSpec\n\n#pragma once\n\n#include <cstddef>\n\nnamespace settings {\n\n",
    );
    format_cpp_scope(&tree, 0, &mut out);
    out.push_str("} // namespace settings\n");
    Ok(out)
}

fn format_cpp_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        let field_name = sanitize_cpp_identifier(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!(
                    "{}inline constexpr std::nullptr_t {} = nullptr;\n",
                    indent, field_name
                ));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in namespace loop below
                TomlValue::Boolean(b) => {
                    out.push_str(&format!(
                        "{}inline constexpr bool {} = {};\n",
                        indent, field_name, b
                    ));
                }
                TomlValue::Array(arr) => {
                    let (type_str, val_str) = cpp_array_literal(arr);
                    out.push_str(&format!(
                        "{}inline constexpr {} {}[] = {};\n",
                        indent, type_str, field_name, val_str
                    ));
                }
                _ => {
                    let (type_str, val_str) = toml_to_cpp_const(v);
                    out.push_str(&format!(
                        "{}inline constexpr {} {} = {};\n",
                        indent, type_str, field_name, val_str
                    ));
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Namespaces next
    for (k, node) in map {
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}namespace {} {{\n",
                    indent,
                    sanitize_cpp_identifier(k)
                ));
                format_cpp_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!(
                    "{}}} // namespace {}\n",
                    indent,
                    sanitize_cpp_identifier(k)
                ));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}namespace {} {{\n",
                    indent,
                    sanitize_cpp_identifier(k)
                ));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_cpp_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!(
                    "{}}} // namespace {}\n",
                    indent,
                    sanitize_cpp_identifier(k)
                ));
            }
            _ => {}
        }
    }
}

fn sanitize_cpp_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "alignas"
            | "alignof"
            | "and"
            | "asm"
            | "auto"
            | "bool"
            | "break"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "concept"
            | "const"
            | "constexpr"
            | "default"
            | "delete"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "explicit"
            | "export"
            | "extern"
            | "false"
            | "float"
            | "for"
            | "friend"
            | "goto"
            | "if"
            | "inline"
            | "int"
            | "long"
            | "mutable"
            | "namespace"
            | "new"
            | "noexcept"
            | "not"
            | "nullptr"
            | "operator"
            | "or"
            | "private"
            | "protected"
            | "public"
            | "register"
            | "requires"
            | "return"
            | "short"
            | "signed"
            | "sizeof"
            | "static"
            | "struct"
            | "switch"
            | "template"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typedef"
            | "typeid"
            | "typename"
            | "union"
            | "unsigned"
            | "using"
            | "virtual"
            | "void"
            | "volatile"
            | "while"
    );

    if is_keyword || !is_valid_identifier(name) {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    } else {
        name.to_string()
    }
}

fn toml_to_cpp_const(v: &TomlValue) -> (&'static str, String) {
    if let Some(literal) = format_scalar_literal(v) {
        match v {
            TomlValue::String(_) | TomlValue::Datetime(_) => ("const char*", literal),
            TomlValue::Integer(_) => ("long long", literal),
            TomlValue::Float(_) => ("double", literal),
            _ => unreachable!(),
        }
    } else {
        match v {
            TomlValue::Boolean(b) => ("bool", b.to_string()),
            _ => ("const char*", "\"\"".to_string()),
        }
    }
}

fn cpp_array_literal(arr: &[TomlValue]) -> (&'static str, String) {
    if arr.is_empty() {
        return ("const char*", "{}".to_string());
    }
    let first = &arr[0];
    let elem_type = match first {
        TomlValue::Integer(_) => "long long",
        TomlValue::Float(_) => "double",
        TomlValue::Boolean(_) => "bool",
        _ => "const char*",
    };
    let items: Vec<String> = arr
        .iter()
        .map(|item| match item {
            TomlValue::Boolean(b) => b.to_string(),
            _ => format_scalar_literal(item).unwrap_or_else(|| "\"\"".to_string()),
        })
        .collect();
    (elem_type, format!("{{ {} }}", items.join(", ")))
}
