use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_elm(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "module Settings exposing (..)\n\n-- Generated by SettingSpec\n\n\nsettings =\n",
    );
    format_elm_record(&tree, 1, &mut out);
    out.push('\n');
    Ok(out)
}

fn format_elm_record(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    if map.is_empty() {
        out.push_str(&format!("{}{{}}", indent));
        return;
    }

    let mut first = true;
    for (k, node) in map {
        let field_name = sanitize_elm_identifier(k);
        let prefix = if first {
            first = false;
            format!("{}{{ ", indent)
        } else {
            format!("{}, ", indent)
        };

        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = Nothing\n", prefix, field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(tbl) => {
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    out.push_str(&format!("{}{} =\n", prefix, field_name));
                    format_elm_record(&sub_map, indent_level + 1, out);
                    out.push('\n');
                }
                _ => {
                    out.push_str(&format!(
                        "{}{} = {}\n",
                        prefix,
                        field_name,
                        toml_to_elm_literal(v)
                    ));
                }
            },
            ConfigNode::Map(sub_map) => {
                out.push_str(&format!("{}{} =\n", prefix, field_name));
                format_elm_record(sub_map, indent_level + 1, out);
                out.push('\n');
            }
        }
    }
    out.push_str(&format!("{}}}", indent));
}

fn sanitize_elm_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "if" | "then"
            | "else"
            | "case"
            | "of"
            | "let"
            | "in"
            | "type"
            | "module"
            | "where"
            | "import"
            | "exposing"
            | "as"
            | "port"
    );

    if is_keyword {
        format!("{}_", name)
    } else if is_valid_identifier(name) && name.chars().next().unwrap().is_ascii_lowercase() {
        name.to_string()
    } else {
        let clean = name.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let mut chars = clean.chars();
        match chars.next() {
            None => "setting".to_string(),
            Some(first) => {
                if first.is_ascii_digit() || first == '_' {
                    format!("k_{}", clean)
                } else {
                    format!("{}{}", first.to_ascii_lowercase(), chars.as_str())
                }
            }
        }
    }
}

fn toml_to_elm_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => {
            if *b {
                "True".to_string()
            } else {
                "False".to_string()
            }
        }
        TomlValue::Array(arr) => {
            let items: Vec<String> = arr.iter().map(toml_to_elm_literal).collect();
            format!("[ {} ]", items.join(", "))
        }
        _ => "\"\"".to_string(),
    }
}
