use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_go(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out =
        String::from("// Code generated by SettingSpec. DO NOT EDIT.\n\npackage settings\n\n");

    let mut const_entries = Vec::new();
    let mut var_entries = Vec::new();
    let mut group_entries = Vec::new();

    for (k, node) in &tree {
        match node {
            ConfigNode::Null => {
                var_entries.push(format!("    {} any = nil", sanitize_go_identifier(k)));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Boolean(b) => {
                    const_entries.push(format!("    {} = {}", sanitize_go_identifier(k), b));
                }
                TomlValue::Array(arr) => {
                    let (type_str, val_str) = go_slice_literal(arr);
                    var_entries.push(format!(
                        "    {} {} = {}",
                        sanitize_go_identifier(k),
                        type_str,
                        val_str
                    ));
                }
                TomlValue::Table(tbl) => {
                    group_entries
                        .push((k.clone(), ConfigNode::Value(TomlValue::Table(tbl.clone()))));
                }
                _ => {
                    if let Some(literal) = format_scalar_literal(v) {
                        const_entries.push(format!(
                            "    {} = {}",
                            sanitize_go_identifier(k),
                            literal
                        ));
                    }
                }
            },
            ConfigNode::Map(_) => {
                group_entries.push((k.clone(), node.clone()));
            }
        }
    }

    if !const_entries.is_empty() {
        out.push_str("const (\n");
        for line in const_entries {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str(")\n\n");
    }

    if !var_entries.is_empty() {
        out.push_str("var (\n");
        for line in var_entries {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str(")\n\n");
    }

    for (k, node) in group_entries {
        let (type_def, val_def) = match node {
            ConfigNode::Map(sub_map) => format_go_struct(&sub_map, 1),
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k, ConfigNode::Value(sub_v));
                }
                format_go_struct(&sub_map, 1)
            }
            _ => unreachable!(),
        };
        out.push_str(&format!(
            "var {} = {}{}\n\n",
            sanitize_go_identifier(&k),
            type_def,
            val_def
        ));
    }

    Ok(out)
}

fn sanitize_go_identifier(name: &str) -> String {
    let s = if is_valid_identifier(name) {
        name.to_string()
    } else {
        name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
    };

    let mut chars = s.chars();
    match chars.next() {
        None => "Setting".to_string(),
        Some(first) => {
            if first.is_ascii_digit() || first == '_' {
                format!("K{}{}", first, chars.as_str())
            } else {
                format!("{}{}", first.to_ascii_uppercase(), chars.as_str())
            }
        }
    }
}

fn go_slice_literal(arr: &[TomlValue]) -> (String, String) {
    if arr.is_empty() {
        return ("[]string".to_string(), "[]string{}".to_string());
    }
    let first = &arr[0];
    let elem_type = match first {
        TomlValue::Integer(_) => "int",
        TomlValue::Float(_) => "float64",
        TomlValue::Boolean(_) => "bool",
        _ => "string",
    };
    let items: Vec<String> = arr
        .iter()
        .map(|v| match v {
            TomlValue::Boolean(b) => b.to_string(),
            _ => format_scalar_literal(v).unwrap_or_else(|| "\"\"".to_string()),
        })
        .collect();
    (
        format!("[]{}", elem_type),
        format!("[]{}{{{}}}", elem_type, items.join(", ")),
    )
}

fn format_go_struct(map: &IndexMap<String, ConfigNode>, indent_level: usize) -> (String, String) {
    let outer_indent = "    ".repeat(indent_level - 1);

    let mut type_fields = Vec::new();
    let mut val_fields = Vec::new();

    for (k, node) in map {
        let field_name = sanitize_go_identifier(k);
        match node {
            ConfigNode::Null => {
                type_fields.push(format!("{}    {} any", outer_indent, field_name));
                val_fields.push(format!("{}    {}: nil,", outer_indent, field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::String(_) | TomlValue::Datetime(_) => {
                    let lit = format_scalar_literal(v).unwrap();
                    type_fields.push(format!("{}    {} string", outer_indent, field_name));
                    val_fields.push(format!("{}    {}: {},", outer_indent, field_name, lit));
                }
                TomlValue::Integer(_) => {
                    let lit = format_scalar_literal(v).unwrap();
                    type_fields.push(format!("{}    {} int", outer_indent, field_name));
                    val_fields.push(format!("{}    {}: {},", outer_indent, field_name, lit));
                }
                TomlValue::Float(_) => {
                    let lit = format_scalar_literal(v).unwrap();
                    type_fields.push(format!("{}    {} float64", outer_indent, field_name));
                    val_fields.push(format!("{}    {}: {},", outer_indent, field_name, lit));
                }
                TomlValue::Boolean(b) => {
                    type_fields.push(format!("{}    {} bool", outer_indent, field_name));
                    val_fields.push(format!("{}    {}: {},", outer_indent, field_name, b));
                }
                TomlValue::Array(arr) => {
                    let (type_str, val_str) = go_slice_literal(arr);
                    type_fields.push(format!("{}    {} {}", outer_indent, field_name, type_str));
                    val_fields.push(format!("{}    {}: {},", outer_indent, field_name, val_str));
                }
                TomlValue::Table(tbl) => {
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    let (sub_type, sub_val) = format_go_struct(&sub_map, indent_level + 1);
                    type_fields.push(format!("{}    {} {}", outer_indent, field_name, sub_type));
                    val_fields.push(format!(
                        "{}    {}: {}{},",
                        outer_indent, field_name, sub_type, sub_val
                    ));
                }
            },
            ConfigNode::Map(sub_map) => {
                let (sub_type, sub_val) = format_go_struct(sub_map, indent_level + 1);
                type_fields.push(format!("{}    {} {}", outer_indent, field_name, sub_type));
                val_fields.push(format!(
                    "{}    {}: {}{},",
                    outer_indent, field_name, sub_type, sub_val
                ));
            }
        }
    }

    let type_str = format!("struct {{\n{}\n{}}}", type_fields.join("\n"), outer_indent);
    let val_str = format!("{{\n{}\n{}}}", val_fields.join("\n"), outer_indent);
    (type_str, val_str)
}
