use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_haskell(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "{-# LANGUAGE DuplicateRecordFields #-}\n\n-- Generated by SettingSpec\n\nmodule Settings where\n\n",
    );

    let mut data_defs = String::new();
    let root_type = generate_haskell_data_types(&tree, "Settings", &mut data_defs);
    out.push_str(&data_defs);

    let mut val_body = String::new();
    format_haskell_record_val(&tree, "Settings", 1, &mut val_body);

    out.push_str(&format!(
        "settings :: {}\nsettings = {}\n",
        root_type, val_body
    ));

    Ok(out)
}

fn generate_haskell_data_types(
    map: &IndexMap<String, ConfigNode>,
    type_name: &str,
    out: &mut String,
) -> String {
    let mut fields = Vec::new();

    for (k, node) in map {
        let field_name = sanitize_haskell_identifier(k);
        match node {
            ConfigNode::Null => {
                fields.push(format!("  , {} :: Maybe String", field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::String(_) | TomlValue::Datetime(_) => {
                    fields.push(format!("  , {} :: String", field_name));
                }
                TomlValue::Integer(_) => {
                    fields.push(format!("  , {} :: Int", field_name));
                }
                TomlValue::Float(_) => {
                    fields.push(format!("  , {} :: Double", field_name));
                }
                TomlValue::Boolean(_) => {
                    fields.push(format!("  , {} :: Bool", field_name));
                }
                TomlValue::Array(arr) => {
                    let type_str = haskell_list_type(arr);
                    fields.push(format!("  , {} :: {}", field_name, type_str));
                }
                TomlValue::Table(tbl) => {
                    let sub_name = format!("{}{}", type_name, capitalize(k));
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    let sub_type = generate_haskell_data_types(&sub_map, &sub_name, out);
                    fields.push(format!("  , {} :: {}", field_name, sub_type));
                }
            },
            ConfigNode::Map(sub_map) => {
                let sub_name = format!("{}{}", type_name, capitalize(k));
                let sub_type = generate_haskell_data_types(sub_map, &sub_name, out);
                fields.push(format!("  , {} :: {}", field_name, sub_type));
            }
        }
    }

    let field_block = if fields.is_empty() {
        format!("data {} = {} deriving (Show, Eq)\n\n", type_name, type_name)
    } else {
        // Change the first comma into a brace
        let mut first = true;
        let mut formatted_fields = Vec::new();
        for f in fields {
            if first {
                first = false;
                formatted_fields.push(format!("  {{ {}", &f[4..]));
            } else {
                formatted_fields.push(f);
            }
        }
        format!(
            "data {} = {}\n{}\n  }} deriving (Show, Eq)\n\n",
            type_name,
            type_name,
            formatted_fields.join("\n")
        )
    };

    out.push_str(&field_block);
    type_name.to_string()
}

fn format_haskell_record_val(
    map: &IndexMap<String, ConfigNode>,
    constructor: &str,
    indent_level: usize,
    out: &mut String,
) {
    let indent = "    ".repeat(indent_level);

    if map.is_empty() {
        out.push_str(constructor);
        return;
    }

    out.push_str(&format!("{}\n{}  {{ ", constructor, indent));

    let mut first = true;
    for (k, node) in map {
        let field_name = sanitize_haskell_identifier(k);
        let prefix = if first {
            first = false;
            String::new()
        } else {
            format!("\n{}  , ", indent)
        };

        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = Nothing", prefix, field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(tbl) => {
                    let sub_constructor = format!("{}{}", constructor, capitalize(k));
                    out.push_str(&format!("{}{} = ", prefix, field_name));
                    let mut sub_map = IndexMap::new();
                    for (sub_k, sub_v) in tbl {
                        sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                    }
                    format_haskell_record_val(&sub_map, &sub_constructor, indent_level + 1, out);
                }
                _ => {
                    out.push_str(&format!(
                        "{}{} = {}",
                        prefix,
                        field_name,
                        toml_to_haskell_literal(v)
                    ));
                }
            },
            ConfigNode::Map(sub_map) => {
                let sub_constructor = format!("{}{}", constructor, capitalize(k));
                out.push_str(&format!("{}{} = ", prefix, field_name));
                format_haskell_record_val(sub_map, &sub_constructor, indent_level + 1, out);
            }
        }
    }
    out.push_str(&format!("\n{}  }}", indent));
}

fn haskell_list_type(arr: &[TomlValue]) -> &'static str {
    if arr.is_empty() {
        return "[String]";
    }
    match &arr[0] {
        TomlValue::Integer(_) => "[Int]",
        TomlValue::Float(_) => "[Double]",
        TomlValue::Boolean(_) => "[Bool]",
        _ => "[String]",
    }
}

fn sanitize_haskell_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "as" | "case"
            | "of"
            | "class"
            | "data"
            | "default"
            | "deriving"
            | "do"
            | "forall"
            | "foreign"
            | "hiding"
            | "if"
            | "then"
            | "else"
            | "import"
            | "infix"
            | "infixl"
            | "infixr"
            | "instance"
            | "let"
            | "in"
            | "mdo"
            | "module"
            | "newtype"
            | "qualified"
            | "type"
            | "where"
    );

    if is_keyword {
        format!("{}_", name)
    } else if is_valid_identifier(name) && name.chars().next().unwrap().is_ascii_lowercase() {
        name.to_string()
    } else {
        let clean = name.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let mut chars = clean.chars();
        match chars.next() {
            None => "setting".to_string(),
            Some(first) => {
                if first.is_ascii_digit() || first == '_' {
                    format!("k_{}", clean)
                } else {
                    format!("{}{}", first.to_ascii_lowercase(), chars.as_str())
                }
            }
        }
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

fn toml_to_haskell_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => {
            if *b {
                "True".to_string()
            } else {
                "False".to_string()
            }
        }
        TomlValue::Array(arr) => {
            let items: Vec<String> = arr.iter().map(toml_to_haskell_literal).collect();
            format!("[{}]", items.join(", "))
        }
        _ => "\"\"".to_string(),
    }
}
