use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_java(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "// Generated by SettingSpec\n\npublic final class Settings {\n    private Settings() {}\n\n",
    );
    format_java_scope(&tree, 1, &mut out);
    out.push_str("}\n");
    Ok(out)
}

fn format_java_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        let field_name = sanitize_java_identifier(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!(
                    "{}public static final Object {} = null;\n",
                    indent, field_name
                ));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in class loop below
                TomlValue::Boolean(b) => {
                    out.push_str(&format!(
                        "{}public static final boolean {} = {};\n",
                        indent, field_name, b
                    ));
                }
                TomlValue::Array(arr) => {
                    let (type_str, val_str) = java_array_literal(arr);
                    out.push_str(&format!(
                        "{}public static final {} {} = {};\n",
                        indent, type_str, field_name, val_str
                    ));
                }
                _ => {
                    let (type_str, val_str) = toml_to_java_const(v);
                    out.push_str(&format!(
                        "{}public static final {} {} = {};\n",
                        indent, type_str, field_name, val_str
                    ));
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Static nested classes next
    for (k, node) in map {
        let class_name = sanitize_java_identifier(k);
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}public static final class {} {{\n{}    private {}() {{}}\n\n",
                    indent, class_name, indent, class_name
                ));
                format_java_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}public static final class {} {{\n{}    private {}() {{}}\n\n",
                    indent, class_name, indent, class_name
                ));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_java_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            _ => {}
        }
    }
}

fn sanitize_java_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "abstract"
            | "assert"
            | "boolean"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extends"
            | "final"
            | "finally"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "implements"
            | "import"
            | "instanceof"
            | "int"
            | "interface"
            | "long"
            | "native"
            | "new"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "short"
            | "static"
            | "strictfp"
            | "super"
            | "switch"
            | "synchronized"
            | "this"
            | "throw"
            | "throws"
            | "transient"
            | "try"
            | "void"
            | "volatile"
            | "while"
            | "record"
            | "yield"
            | "var"
            | "null"
            | "true"
            | "false"
    );

    if is_keyword || !is_valid_identifier(name) {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    } else {
        name.to_string()
    }
}

fn toml_to_java_const(v: &TomlValue) -> (&'static str, String) {
    if let Some(literal) = format_scalar_literal(v) {
        match v {
            TomlValue::String(_) | TomlValue::Datetime(_) => ("String", literal),
            TomlValue::Integer(_) => ("long", format!("{}L", literal)),
            TomlValue::Float(_) => ("double", literal),
            _ => unreachable!(),
        }
    } else {
        match v {
            TomlValue::Boolean(b) => ("boolean", b.to_string()),
            _ => ("String", "\"\"".to_string()),
        }
    }
}

fn java_array_literal(arr: &[TomlValue]) -> (&'static str, String) {
    if arr.is_empty() {
        return ("String[]", "new String[0]".to_string());
    }
    let first = &arr[0];
    let (elem_type, array_type) = match first {
        TomlValue::Integer(_) => ("long", "long[]"),
        TomlValue::Float(_) => ("double", "double[]"),
        TomlValue::Boolean(_) => ("boolean", "boolean[]"),
        _ => ("String", "String[]"),
    };
    let items: Vec<String> = arr
        .iter()
        .map(|item| match item {
            TomlValue::Integer(i) => format!("{}L", i),
            TomlValue::Boolean(b) => b.to_string(),
            _ => format_scalar_literal(item).unwrap_or_else(|| "\"\"".to_string()),
        })
        .collect();
    (
        array_type,
        format!("new {}[] {{ {} }}", elem_type, items.join(", ")),
    )
}
