use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_lua(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("-- Generated by SettingSpec\n\nreturn ");
    format_lua_table(&tree, 0, &mut out);
    out.push('\n');
    Ok(out)
}

fn format_lua_table(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "  ".repeat(indent_level);
    let inner_indent = "  ".repeat(indent_level + 1);

    if map.is_empty() {
        out.push_str("{}");
        return;
    }

    out.push_str("{\n");
    for (k, node) in map {
        let key_str = sanitize_lua_key(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = nil,\n", inner_indent, key_str));
            }
            ConfigNode::Value(v) => {
                out.push_str(&format!(
                    "{}{} = {},\n",
                    inner_indent,
                    key_str,
                    toml_to_lua_literal(v)
                ));
            }
            ConfigNode::Map(sub_map) => {
                out.push_str(&format!("{}{} = ", inner_indent, key_str));
                format_lua_table(sub_map, indent_level + 1, out);
                out.push_str(",\n");
            }
        }
    }
    out.push_str(&format!("{}}}", indent));
}

fn sanitize_lua_key(key: &str) -> String {
    if is_valid_identifier(key) {
        key.to_string()
    } else {
        format!("[\"{}\"]", key)
    }
}

fn toml_to_lua_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => {
            if *b {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        TomlValue::Array(arr) => {
            let items: Vec<String> = arr.iter().map(toml_to_lua_literal).collect();
            format!("{{ {} }}", items.join(", "))
        }
        TomlValue::Table(tbl) => {
            let items: Vec<String> = tbl
                .iter()
                .map(|(k, v)| format!("{} = {}", sanitize_lua_key(k), toml_to_lua_literal(v)))
                .collect();
            format!("{{ {} }}", items.join(", "))
        }
        _ => unreachable!("scalars are handled by format_scalar_literal"),
    }
}
