use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_python(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("# Generated by SettingSpec\n\n");
    format_python_scope(&tree, 0, &mut out);
    Ok(out)
}

fn format_python_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    if map.is_empty() && indent_level > 0 {
        out.push_str(&format!("{}pass\n", indent));
        return;
    }

    // First write scalar/leaf assignments
    for (k, node) in map {
        match node {
            ConfigNode::Map(_) => {}
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = None\n", indent, sanitize_identifier(k)));
            }
            ConfigNode::Value(v) => {
                out.push_str(&format!(
                    "{}{} = {}\n",
                    indent,
                    sanitize_identifier(k),
                    toml_to_python_literal(v)
                ));
            }
        }
    }

    // Then write nested classes
    for (k, node) in map {
        if let ConfigNode::Map(sub_map) = node {
            if indent_level == 0 && !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(&format!("{}class {}:\n", indent, sanitize_identifier(k)));
            format_python_scope(sub_map, indent_level + 1, out);
            if indent_level == 0 {
                out.push('\n');
            }
        }
    }
}

fn sanitize_identifier(name: &str) -> String {
    if is_valid_identifier(name) {
        name.to_string()
    } else {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    }
}

fn toml_to_python_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => {
            if *b {
                "True".to_string()
            } else {
                "False".to_string()
            }
        }
        TomlValue::Array(arr) => {
            let items: Vec<String> = arr.iter().map(toml_to_python_literal).collect();
            format!("[{}]", items.join(", "))
        }
        TomlValue::Table(tbl) => {
            let items: Vec<String> = tbl
                .iter()
                .map(|(k, v)| {
                    format!(
                        "{}: {}",
                        serde_json::to_string(k).unwrap(),
                        toml_to_python_literal(v)
                    )
                })
                .collect();
            format!("{{{}}}", items.join(", "))
        }
        _ => unreachable!("scalars are handled by format_scalar_literal"),
    }
}
