use super::common::format_scalar_literal;
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_ruby(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("# Generated by SettingSpec\n\nmodule Settings\n");
    format_ruby_scope(&tree, 1, &mut out);
    out.push_str("end\n");
    Ok(out)
}

fn format_ruby_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "  ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        let const_name = to_ruby_const_name(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = nil\n", indent, const_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in module loop below
                TomlValue::Boolean(b) => {
                    out.push_str(&format!("{}{} = {}\n", indent, const_name, b));
                }
                TomlValue::Array(arr) => {
                    let items: Vec<String> = arr.iter().map(toml_to_ruby_literal).collect();
                    out.push_str(&format!(
                        "{}{} = [{}].freeze\n",
                        indent,
                        const_name,
                        items.join(", ")
                    ));
                }
                TomlValue::String(_) | TomlValue::Datetime(_) => {
                    let lit = format_scalar_literal(v).unwrap();
                    out.push_str(&format!("{}{} = {}.freeze\n", indent, const_name, lit));
                }
                _ => {
                    if let Some(lit) = format_scalar_literal(v) {
                        out.push_str(&format!("{}{} = {}\n", indent, const_name, lit));
                    }
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Nested modules next
    for (k, node) in map {
        let mod_name = to_ruby_module_name(k);
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("Settings\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}module {}\n", indent, mod_name));
                format_ruby_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}end\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("Settings\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}module {}\n", indent, mod_name));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_ruby_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}end\n", indent));
            }
            _ => {}
        }
    }
}

fn to_ruby_const_name(name: &str) -> String {
    let clean = name.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
    let upper = clean.to_ascii_uppercase();
    if upper
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_digit() || c == '_')
    {
        format!("K_{}", upper)
    } else {
        upper
    }
}

fn to_ruby_module_name(name: &str) -> String {
    let clean = name.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
    let parts: Vec<&str> = clean.split('_').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() {
        return "Group".to_string();
    }
    let mut result = String::new();
    for part in parts {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.push_str(chars.as_str());
        }
    }
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("G{}", result)
    } else {
        result
    }
}

fn toml_to_ruby_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        match v {
            TomlValue::String(_) | TomlValue::Datetime(_) => format!("{}.freeze", literal),
            _ => literal,
        }
    } else {
        match v {
            TomlValue::Boolean(b) => b.to_string(),
            TomlValue::Array(arr) => {
                let items: Vec<String> = arr.iter().map(toml_to_ruby_literal).collect();
                format!("[{}].freeze", items.join(", "))
            }
            _ => "\"\"".to_string(),
        }
    }
}
