use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_rust(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from(
        "// Generated by SettingSpec\n\n#![allow(dead_code, non_snake_case, non_upper_case_globals)]\n\n",
    );
    format_rust_scope(&tree, 0, &mut out);
    Ok(out)
}

fn format_rust_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        match node {
            ConfigNode::Null => {
                out.push_str(&format!(
                    "{}pub const {}: Option<&'static str> = None;\n",
                    indent,
                    sanitize_rust_identifier(k)
                ));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in module loop below
                _ => {
                    let (type_str, val_str) = toml_to_rust_const(v);
                    out.push_str(&format!(
                        "{}pub const {}: {} = {};\n",
                        indent,
                        sanitize_rust_identifier(k),
                        type_str,
                        val_str
                    ));
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Submodules next
    for (k, node) in map {
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}pub mod {} {{\n",
                    indent,
                    sanitize_rust_identifier(k)
                ));
                format_rust_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}pub mod {} {{\n",
                    indent,
                    sanitize_rust_identifier(k)
                ));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_rust_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            _ => {}
        }
    }
}

fn sanitize_rust_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    );

    if is_keyword {
        format!("r#{}", name)
    } else if is_valid_identifier(name) {
        name.to_string()
    } else {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    }
}

fn toml_to_rust_const(v: &TomlValue) -> (&'static str, String) {
    if let Some(literal) = format_scalar_literal(v) {
        match v {
            TomlValue::String(_) | TomlValue::Datetime(_) => ("&'static str", literal),
            TomlValue::Integer(_) => ("i64", literal),
            TomlValue::Float(_) => ("f64", literal),
            _ => unreachable!(),
        }
    } else {
        match v {
            TomlValue::Boolean(b) => ("bool", b.to_string()),
            TomlValue::Array(arr) => {
                if arr.is_empty() {
                    ("&'static [&'static str]", "&[]".to_string())
                } else {
                    let first = &arr[0];
                    let elem_type = match first {
                        TomlValue::Integer(_) => "i64",
                        TomlValue::Float(_) => "f64",
                        TomlValue::Boolean(_) => "bool",
                        _ => "&'static str",
                    };
                    let items: Vec<String> = arr
                        .iter()
                        .map(|item| {
                            let (_, val) = toml_to_rust_const(item);
                            val
                        })
                        .collect();
                    let type_str = match elem_type {
                        "i64" => "&'static [i64]",
                        "f64" => "&'static [f64]",
                        "bool" => "&'static [bool]",
                        _ => "&'static [&'static str]",
                    };
                    (type_str, format!("&[{}]", items.join(", ")))
                }
            }
            _ => ("&'static str", "\"\"".to_string()),
        }
    }
}
