use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_scala(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("// Generated by SettingSpec\n\nobject Settings {\n");
    format_scala_scope(&tree, 1, &mut out);
    out.push_str("}\n");
    Ok(out)
}

fn format_scala_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "  ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        let field_name = sanitize_scala_identifier(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!(
                    "{}final val {}: Option[String] = None\n",
                    indent, field_name
                ));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in object loop below
                TomlValue::Boolean(b) => {
                    out.push_str(&format!(
                        "{}final val {}: Boolean = {}\n",
                        indent, field_name, b
                    ));
                }
                TomlValue::Array(arr) => {
                    let (type_str, val_str) = scala_array_literal(arr);
                    out.push_str(&format!(
                        "{}val {}: {} = {}\n",
                        indent, field_name, type_str, val_str
                    ));
                }
                _ => {
                    let (type_str, val_str) = toml_to_scala_const(v);
                    out.push_str(&format!(
                        "{}final val {}: {} = {}\n",
                        indent, field_name, type_str, val_str
                    ));
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Nested singleton objects next
    for (k, node) in map {
        let obj_name = sanitize_scala_identifier(k);
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}object {} {{\n", indent, obj_name));
                format_scala_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}object {} {{\n", indent, obj_name));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_scala_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            _ => {}
        }
    }
}

fn sanitize_scala_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "abstract"
            | "case"
            | "catch"
            | "class"
            | "def"
            | "do"
            | "else"
            | "extends"
            | "false"
            | "final"
            | "finally"
            | "for"
            | "forSome"
            | "if"
            | "implicit"
            | "import"
            | "lazy"
            | "match"
            | "new"
            | "null"
            | "object"
            | "override"
            | "package"
            | "private"
            | "protected"
            | "return"
            | "sealed"
            | "super"
            | "this"
            | "throw"
            | "trait"
            | "try"
            | "true"
            | "type"
            | "val"
            | "var"
            | "while"
            | "with"
            | "yield"
    );

    if is_keyword {
        format!("`{}`", name)
    } else if is_valid_identifier(name) {
        name.to_string()
    } else {
        format!(
            "_{}",
            name.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
        )
    }
}

fn toml_to_scala_const(v: &TomlValue) -> (&'static str, String) {
    if let Some(literal) = format_scalar_literal(v) {
        match v {
            TomlValue::String(_) | TomlValue::Datetime(_) => ("String", literal),
            TomlValue::Integer(_) => ("Long", format!("{}L", literal)),
            TomlValue::Float(_) => ("Double", literal),
            _ => unreachable!(),
        }
    } else {
        match v {
            TomlValue::Boolean(b) => ("Boolean", b.to_string()),
            _ => ("String", "\"\"".to_string()),
        }
    }
}

fn scala_array_literal(arr: &[TomlValue]) -> (&'static str, String) {
    if arr.is_empty() {
        return ("List[String]", "List.empty[String]".to_string());
    }
    let first = &arr[0];
    let (_elem_type, list_type) = match first {
        TomlValue::Integer(_) => ("Long", "List[Long]"),
        TomlValue::Float(_) => ("Double", "List[Double]"),
        TomlValue::Boolean(_) => ("Boolean", "List[Boolean]"),
        _ => ("String", "List[String]"),
    };
    let items: Vec<String> = arr
        .iter()
        .map(|item| match item {
            TomlValue::Integer(i) => format!("{}L", i),
            TomlValue::Boolean(b) => b.to_string(),
            _ => format_scalar_literal(item).unwrap_or_else(|| "\"\"".to_string()),
        })
        .collect();
    (list_type, format!("List({})", items.join(", ")))
}
