use super::common::format_scalar_literal;
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_terraform(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("# Generated by SettingSpec\n\nlocals {\n");
    format_terraform_scope(&tree, 1, &mut out);
    out.push_str("}\n");
    Ok(out)
}

fn format_terraform_scope(
    map: &IndexMap<String, ConfigNode>,
    indent_level: usize,
    out: &mut String,
) {
    let indent = "  ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        let field_name = sanitize_hcl_key(k);
        match node {
            ConfigNode::Null => {
                out.push_str(&format!("{}{} = null\n", indent, field_name));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled below
                TomlValue::Boolean(b) => {
                    out.push_str(&format!("{}{} = {}\n", indent, field_name, b));
                }
                TomlValue::Array(arr) => {
                    let items: Vec<String> = arr.iter().map(toml_to_hcl_literal).collect();
                    out.push_str(&format!(
                        "{}{} = [{}]\n",
                        indent,
                        field_name,
                        items.join(", ")
                    ));
                }
                _ => {
                    if let Some(lit) = format_scalar_literal(v) {
                        out.push_str(&format!("{}{} = {}\n", indent, field_name, lit));
                    }
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Nested blocks / maps next
    for (k, node) in map {
        let field_name = sanitize_hcl_key(k);
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}{} = {{\n", indent, field_name));
                format_terraform_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!("{}{} = {{\n", indent, field_name));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_terraform_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}}\n", indent));
            }
            _ => {}
        }
    }
}

fn sanitize_hcl_key(name: &str) -> String {
    let is_simple = !name.is_empty()
        && !name.chars().next().unwrap().is_ascii_digit()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-');

    if is_simple {
        name.to_string()
    } else {
        serde_json::to_string(name).unwrap()
    }
}

fn toml_to_hcl_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => b.to_string(),
        TomlValue::Array(arr) => {
            let items: Vec<String> = arr.iter().map(toml_to_hcl_literal).collect();
            format!("[{}]", items.join(", "))
        }
        TomlValue::Table(tbl) => {
            let mut entries = Vec::new();
            for (k, val) in tbl {
                entries.push(format!(
                    "{} = {}",
                    sanitize_hcl_key(k),
                    toml_to_hcl_literal(val)
                ));
            }
            format!("{{ {} }}", entries.join(", "))
        }
        _ => "\"\"".to_string(),
    }
}
