use super::common::is_valid_identifier;
use super::json::generate_json;
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_typescript(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut interfaces = String::new();
    let root_type = generate_ts_interfaces(&tree, "Settings", &mut interfaces);

    let json_val = generate_json(settings)?;
    let mut out = String::new();
    out.push_str("// Generated by SettingSpec\n\n");
    out.push_str(&interfaces);
    out.push_str(&format!(
        "\nconst settings: {} = {};\n\nexport default settings;\n",
        root_type, json_val
    ));
    Ok(out)
}

fn generate_ts_interfaces(
    map: &IndexMap<String, ConfigNode>,
    interface_name: &str,
    out: &mut String,
) -> String {
    let mut fields = Vec::new();

    for (k, node) in map {
        match node {
            ConfigNode::Null => {
                fields.push(format!("  {}: null;", sanitize_ts_key(k)));
            }
            ConfigNode::Value(v) => {
                fields.push(format!("  {}: {};", sanitize_ts_key(k), ts_type_of(v)));
            }
            ConfigNode::Map(sub_map) => {
                let sub_name = format!("{}{}", interface_name, capitalize(k));
                let sub_type = generate_ts_interfaces(sub_map, &sub_name, out);
                fields.push(format!("  {}: {};", sanitize_ts_key(k), sub_type));
            }
        }
    }

    let iface = format!(
        "export interface {} {{\n{}\n}}\n",
        interface_name,
        fields.join("\n")
    );
    out.push_str(&iface);
    interface_name.to_string()
}

fn sanitize_ts_key(key: &str) -> String {
    if is_valid_identifier(key) {
        key.to_string()
    } else {
        format!("\"{}\"", key)
    }
}

fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

fn ts_type_of(v: &TomlValue) -> &'static str {
    match v {
        TomlValue::String(_) | TomlValue::Datetime(_) => "string",
        TomlValue::Integer(_) | TomlValue::Float(_) => "number",
        TomlValue::Boolean(_) => "boolean",
        TomlValue::Array(_) => "any[]",
        TomlValue::Table(_) => "Record<string, any>",
    }
}
