use super::common::{format_scalar_literal, is_valid_identifier};
use super::tree::{ConfigNode, build_config_tree};
use crate::error::Result;
use crate::model::ResolvedSetting;
use indexmap::IndexMap;
use toml::Value as TomlValue;

pub fn generate_zig(settings: &[ResolvedSetting]) -> Result<String> {
    let tree = build_config_tree(settings, false);
    let mut out = String::from("// Generated by SettingSpec\n\n");
    format_zig_scope(&tree, 0, &mut out);
    Ok(out)
}

fn format_zig_scope(map: &IndexMap<String, ConfigNode>, indent_level: usize, out: &mut String) {
    let indent = "    ".repeat(indent_level);

    // Leaf/scalar constants first
    for (k, node) in map {
        match node {
            ConfigNode::Null => {
                out.push_str(&format!(
                    "{}pub const {} = null;\n",
                    indent,
                    sanitize_zig_identifier(k)
                ));
            }
            ConfigNode::Value(v) => match v {
                TomlValue::Table(_) => {} // Handled in struct loop below
                _ => {
                    let val_str = toml_to_zig_literal(v);
                    out.push_str(&format!(
                        "{}pub const {} = {};\n",
                        indent,
                        sanitize_zig_identifier(k),
                        val_str
                    ));
                }
            },
            ConfigNode::Map(_) => {}
        }
    }

    // Nested structs next
    for (k, node) in map {
        match node {
            ConfigNode::Map(sub_map) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}pub const {} = struct {{\n",
                    indent,
                    sanitize_zig_identifier(k)
                ));
                format_zig_scope(sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}};\n", indent));
            }
            ConfigNode::Value(TomlValue::Table(tbl)) => {
                if !out.ends_with("\n\n") && !out.ends_with("{\n") {
                    out.push('\n');
                }
                out.push_str(&format!(
                    "{}pub const {} = struct {{\n",
                    indent,
                    sanitize_zig_identifier(k)
                ));
                let mut sub_map = IndexMap::new();
                for (sub_k, sub_v) in tbl {
                    sub_map.insert(sub_k.clone(), ConfigNode::Value(sub_v.clone()));
                }
                format_zig_scope(&sub_map, indent_level + 1, out);
                out.push_str(&format!("{}}};\n", indent));
            }
            _ => {}
        }
    }
}

fn sanitize_zig_identifier(name: &str) -> String {
    let is_keyword = matches!(
        name,
        "addrspace"
            | "align"
            | "allowzero"
            | "and"
            | "anyframe"
            | "anytype"
            | "asm"
            | "async"
            | "await"
            | "break"
            | "callconv"
            | "catch"
            | "comptime"
            | "const"
            | "continue"
            | "defer"
            | "else"
            | "enum"
            | "errdefer"
            | "error"
            | "export"
            | "extern"
            | "fn"
            | "for"
            | "if"
            | "inline"
            | "noalias"
            | "noinline"
            | "nosuspend"
            | "opaque"
            | "or"
            | "orelse"
            | "packed"
            | "pub"
            | "resume"
            | "return"
            | "linksection"
            | "struct"
            | "suspend"
            | "switch"
            | "test"
            | "threadlocal"
            | "try"
            | "union"
            | "unreachable"
            | "usingnamespace"
            | "var"
            | "volatile"
            | "while"
            | "null"
            | "true"
            | "false"
    );

    if !is_keyword && is_valid_identifier(name) {
        name.to_string()
    } else {
        format!("@\"{}\"", name)
    }
}

fn toml_to_zig_literal(v: &TomlValue) -> String {
    if let Some(literal) = format_scalar_literal(v) {
        return literal;
    }
    match v {
        TomlValue::Boolean(b) => b.to_string(),
        TomlValue::Array(arr) => {
            if arr.is_empty() {
                "[_][]const u8{}".to_string()
            } else {
                let first = &arr[0];
                let type_prefix = match first {
                    TomlValue::Integer(_) => "[_]i64",
                    TomlValue::Float(_) => "[_]f64",
                    TomlValue::Boolean(_) => "[_]bool",
                    _ => "[_][]const u8",
                };
                let items: Vec<String> = arr.iter().map(toml_to_zig_literal).collect();
                format!("{}{{ {} }}", type_prefix, items.join(", "))
            }
        }
        _ => "\"\"".to_string(),
    }
}
