name: SettingSpec Check
on: [push, pull_request]
permissions:
  contents: read
  packages: read
jobs:
  check-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Check settingspec.toml
        run: docker run --rm -v "${{ github.workspace }}:/app" ghcr.io/sayanarijit/settingspec:main check
